export const checked = "2026-09-06";
export const categories = ["Synthetic respondents", "Digital twins", "Sample augmentation", "Audience simulation"] as const;
export type Category = typeof categories[number];
export type Product = {
  slug: string; company: string; name: string; category: Category;
  summary: string; data: string; access: string; pricing: string;
  uses: string[]; question: string; source: string; sourceTitle: string; color: string;
};
export const products: Product[] = [
  { slug: "aaru", company: "Aaru", name: "Behavior simulation", category: "Audience simulation", color: "#ce4936",
    summary: "Population simulations for product, pricing, messaging and strategic decisions.",
    data: "Aaru describes populations grounded in demographic, behavioral and outcomes data.", access: "Contact sales", pricing: "Discuss scope with provider",
    uses: ["Concept testing", "Scenario planning"], question: "Which observed outcomes and holdout populations match the decision you want to simulate?",
    source: "https://aaru.com/simulation", sourceTitle: "Aaru: Simulation" },
  { slug: "delve-ai", company: "Delve AI", name: "Synthetic Users", category: "Synthetic respondents", color: "#24694d",
    summary: "AI-generated participants for surveys, interviews and product-concept feedback.",
    data: "The provider connects its synthetic-user offer with its customer-persona products.", access: "Subscription", pricing: "Advertised from US$99/month for 100 synthetic users; confirm inclusions",
    uses: ["Concept testing", "Exploratory interviews"], question: "What does a synthetic-user allowance include, and which research functions require a separate plan?",
    source: "https://www.delve.ai/synthetic-users", sourceTitle: "Delve AI: Synthetic Users" },
  { slug: "electric-twin", company: "Electric Twin", name: "Synthetic audiences", category: "Audience simulation", color: "#2d6958",
    summary: "An audience workspace for asking new questions of models built around customer research.",
    data: "Electric Twin describes using surveys, focus groups and customer interviews to construct audiences.", access: "Contact sales", pricing: "Discuss scope with provider",
    uses: ["Concept testing", "Segmentation activation"], question: "Can you inspect audience-specific holdout results, including errors on your smallest decision-critical groups?",
    source: "https://www.electrictwin.com/", sourceTitle: "Electric Twin: platform and FAQs" },
  { slug: "fairgen-boost", company: "Fairgen", name: "Boost", category: "Sample augmentation", color: "#366646",
    summary: "Synthetic expansion of existing survey samples for deeper subgroup analysis.",
    data: "The provider positions Boost as a hybrid tool working from existing research samples.", access: "Contact sales", pricing: "Discuss scope with provider",
    uses: ["Subgroup analysis"], question: "What starting sample and subgroup sizes are required, and how is uncertainty calculated after boosting?",
    source: "https://www.fairgen.ai/", sourceTitle: "Fairgen: research toolkit" },
  { slug: "fairgen-twins", company: "Fairgen", name: "Twins", category: "Digital twins", color: "#366646",
    summary: "Simulated respondents from partner audiences or your own quantitative and qualitative research.",
    data: "Fairgen describes individual-level panel data and optional interview transcripts as inputs.", access: "Contact sales", pricing: "Discuss scope with provider",
    uses: ["Concept testing", "Exploratory interviews"], question: "Which topics were measured in the original study, and which new questions require fresh fieldwork?",
    source: "https://www.fairgen.ai/", sourceTitle: "Fairgen: Twins FAQs" },
  { slug: "ipsos-personabot", company: "Ipsos", name: "PersonaBot", category: "Digital twins", color: "#344f9c",
    summary: "Conversational access to personas from segmentation studies, including consumer and healthcare applications.",
    data: "Ipsos describes PersonaBot as a way to interact with personas identified in an existing segmentation study.", access: "Research engagement", pricing: "Discuss scope with provider",
    uses: ["Segmentation activation"], question: "How are persona answers linked to measured segment characteristics rather than generated inference?",
    source: "https://www.ipsos.com/en/launch-ipsos-personabot-groundbreaking-ai-powered-solution-enhance-segmentation-research", sourceTitle: "Ipsos: PersonaBot launch, 2 July 2024" },
  { slug: "panoplai", company: "Panoplai", name: "Digital Twins", category: "Digital twins", color: "#9b405d",
    summary: "Audience segment conversations alongside survey collection, data ingestion and reporting.",
    data: "Panoplai describes first-party data and known demographics as the grounding for its AI research platform.", access: "Contact sales", pricing: "Discuss scope with provider",
    uses: ["Segmentation activation", "Concept testing"], question: "Which outputs come from collected responses, enrichment or simulated twins, and can you separate them in exports?",
    source: "https://www.panoplai.com/", sourceTitle: "Panoplai: platform overview" },
  { slug: "qualtrics-synthetic-panels", company: "Qualtrics", name: "Synthetic Panels", category: "Synthetic respondents", color: "#1b62a8",
    summary: "Synthetic survey responses within Qualtrics, with documented survey-feature compatibility.",
    data: "Qualtrics describes a proprietary model trained on survey responses. Its documented panel covers the US general population in English.", access: "Subscription credits", pricing: "Edge Qualtrics Audiences credits through an account executive",
    uses: ["Concept testing", "Survey research"], question: "Does your questionnaire fit the supported features? Documentation excludes image understanding and incidence below 80%.",
    source: "https://www.qualtrics.com/support/survey-platform/distributions-module/synthetic-panels/", sourceTitle: "Qualtrics: Synthetic Panels documentation" },
  { slug: "simile", company: "Simile", name: "Behavioral simulation", category: "Audience simulation", color: "#8b503b",
    summary: "Human-behavior simulations designed to explore reactions to changing products, prices and policies.",
    data: "Simile describes combining observed behavior with surveys, interviews and experiments.", access: "Contact sales", pricing: "Discuss scope with provider",
    uses: ["Scenario planning", "Concept testing"], question: "How is confidence assessed when a proposed change differs from the situations observed in training?",
    source: "https://www.simile.com/blog/what-if-machine", sourceTitle: "Simile: Building the What-If Machine" },
  { slug: "synthetic-users", company: "Synthetic Users", name: "Synthetic Users", category: "Synthetic respondents", color: "#ac4144",
    summary: "Persona-based research studies, interviews and surveys with developer API access.",
    data: "The documentation describes synthetic personas generated from audience definitions.", access: "Platform and API", pricing: "Confirm current plan with provider",
    uses: ["Exploratory interviews", "Survey research"], question: "How can supplied audience definitions be grounded in your own research, and what evidence supports the intended use?",
    source: "https://docs.syntheticusers.com/guides/core-concepts", sourceTitle: "Synthetic Users: Core Concepts" },
  { slug: "toluna-boost", company: "Toluna", name: "HarmonAIze Boost", category: "Sample augmentation", color: "#274ba7",
    summary: "Post-fieldwork synthetic augmentation for smaller or hard-to-reach survey groups.",
    data: "Toluna defines Boost as amplifying patterns in existing collected data, rather than recruiting new respondents.", access: "Research engagement", pricing: "Discuss scope with provider",
    uses: ["Subgroup analysis"], question: "Which original observations support the boosted group, and how are multivariate relationships evaluated?",
    source: "https://tolunacorporate.com/wp-content/uploads/2025/04/Toluna-Group-Terms-of-Business-v2.6_Incl.-HarmonAize_140325_FINAL.pdf", sourceTitle: "Toluna: terms and product definitions, March 2025" },
  { slug: "toluna-personas", company: "Toluna", name: "Synthetic Personas", category: "Synthetic respondents", color: "#274ba7",
    summary: "Synthetic survey-taking personas for screening claims, ideas, flavors and brand messages.",
    data: "Toluna describes anonymized first-party panel data as the basis for its synthetic personas.", access: "Contact sales", pricing: "Discuss scope with provider",
    uses: ["Concept testing", "Survey research"], question: "Which countries, languages and stimulus formats have been validated for the persona product you are buying?",
    source: "https://tolunacorporate.com/ai-and-innovation/toluna-synthetic-personas/", sourceTitle: "Toluna: Synthetic Personas" },
  { slug: "yabble", company: "Yabble", name: "Virtual Audiences", category: "Audience simulation", color: "#965424",
    summary: "AI-generated audiences for exploratory research and concept feedback, including visual stimuli.",
    data: "Yabble describes an augmented model combining LLMs with trend, social and behavioral information.", access: "Platform", pricing: "Confirm current plan with provider",
    uses: ["Concept testing", "Exploratory interviews"], question: "Which data sources support this audience, how recent are they, and how are generated findings validated?",
    source: "https://www.yabble.com/virtual-audiences", sourceTitle: "Yabble: Virtual Audiences and FAQs" },
];
export const uses = [...new Set(products.flatMap(p => p.uses))].sort();
export const providerCount = new Set(products.map(p => p.company)).size;
export function getProduct(slug: string) { return products.find(p => p.slug === slug); }
export const categoryDescriptions: Record<Category, string> = {
  "Synthetic respondents": "AI-generated participants answering interview or survey questions.",
  "Digital twins": "Conversational models of people or segments grounded in research data.",
  "Sample augmentation": "Models that extend or enrich an existing collected dataset.",
  "Audience simulation": "Modeled populations used to explore decisions and possible responses.",
};
