export type Guidance = { id: string; institution: string; title: string; topic: string; format: string; summary: string; source: string };
export const guidance: Guidance[] = [
  { id: "esomar-ai-buyers", institution: "ESOMAR", title: "20 questions for buying AI-based research", topic: "Buying tools", format: "Buyer checklist", summary: "A starting point for conversations with AI research suppliers: how the service works, what data it uses, who is accountable and how outputs are checked.", source: "https://esomar.org/publications/esomar-20-questions-to-help-buyers-of-ai-based-services" },
  { id: "esomar-augmentation", institution: "ESOMAR", title: "Buying augmented synthetic data", topic: "Sample augmentation", format: "Discussion guide", summary: "Five topics to work through with a supplier when synthetic data will extend an existing research sample.", source: "https://esocorpwebsitestg.blob.core.windows.net/strapi-uploads/uploads/ESOMAR_5_Topics_of_Discussion_to_Help_Buyers_of_Augmented_Synthetic_Data_bc665edbbd.pdf" },
  { id: "mrs-ai", institution: "Market Research Society", title: "Using AI and related technologies in research", topic: "Research practice", format: "Professional guidance", summary: "MRS guidance for researchers applying AI, including responsibilities for research quality, participant protection and explaining the methods used.", source: "https://www.mrs.org.uk/standards/guidance-on-using-ai-and-related-technologies" },
  { id: "mrs-esomar-consent", institution: "MRS and ESOMAR", title: "Client data, AI and the boundaries of consent", topic: "Consent and privacy", format: "Joint guidance", summary: "A practical note on what client contracts and participant consent allow when research data is reused in AI systems.", source: "https://www.mrs.org.uk/standards/mrs-and-esomar-client-data-ai-statement-" },
  { id: "ia-synthetic", institution: "Insights Association", title: "How the research code applies to synthetic data", topic: "Research practice", format: "Code in Action", summary: "The June 2026 update explains how consent, privacy, validation and disclosure obligations apply to synthetic participants and digital twins.", source: "https://www.insightsassociation.org/News-Updates/Articles/ArticleID/2614/Code-in-Action-Synthetic-Data-Revisited" },
  { id: "aapor-ai", institution: "AAPOR", title: "Responsible AI integration in survey research", topic: "Research practice", format: "Task force report", summary: "A 2026 review of AI across questionnaire design, interviewing, processing, analysis and reporting, with a framework for responsible adoption.", source: "https://aapor.org/announcements/task-force-on-responsible-ai-integration-in-survey-research-report/" },
  { id: "gdq-resources", institution: "Global Data Quality", title: "Data quality resources for research teams", topic: "Data quality", format: "Resource library", summary: "A cross-association collection covering participant engagement, sample quality, fraud and AI, including practical documents from several research bodies.", source: "https://www.globaldataquality.org/GDQ-resources" },
  { id: "ico-synthetic", institution: "Information Commissioner's Office", title: "Synthetic data and privacy-enhancing technologies", topic: "Consent and privacy", format: "Regulator guidance", summary: "Explains privacy-enhancing technologies, including synthetic data, and the risks to assess when using them to share or analyze information.", source: "https://ico.org.uk/media/for-organisations/uk-gdpr-guidance-and-resources/data-sharing/privacy-enhancing-technologies-1-0.pdf" },
  { id: "nist-genai", institution: "NIST", title: "Managing the risks of generative AI", topic: "AI governance", format: "Cross-sector framework", summary: "The Generative AI Profile sets out risks and suggested actions across an AI system's life cycle. Useful for teams designing procurement and review policies.", source: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence" },
  { id: "nist-playbook", institution: "NIST", title: "AI risk management playbook", topic: "AI governance", format: "Implementation playbook", summary: "Suggested actions and documentation practices for putting the AI Risk Management Framework to work within an organization.", source: "https://www.nist.gov/itl/ai-risk-management-framework/nist-ai-rmf-playbook" },
];
