export type Story = { slug: string; type: "Buyer guide" | "Analysis" | "Briefing"; title: string; dek: string; minutes: number; sections: { title: string; text: string }[]; sources: { title: string; url: string }[]; related: string[] };
export const stories: Story[] = [
  { slug: "choose-the-right-synthetic-research", type: "Buyer guide", title: "Four kinds of synthetic research. Four different buying decisions.", dek: "A simulated respondent, a segment twin and a boosted sample are not interchangeable. Start with the job you need done.", minutes: 4,
    sections: [
      { title: "Start with the output", text: "Write down the decision before looking at a demo. Are you exploring possible reactions, bringing a segmentation to life, extending a collected dataset or comparing future scenarios? Those jobs require different evidence. A fluent conversation can help expose questions without establishing how common an opinion is." },
      { title: "Respondents answer. Twins contextualize.", text: "Synthetic respondents generate survey or interview responses. Qualtrics documents this as a survey-platform feature; Synthetic Users describes personas created from audience definitions. Digital-twin products often begin with an existing person or segment dataset. Ipsos PersonaBot, for example, is positioned around activating segmentation studies. Product names alone do not establish the underlying method. [1, 2, 3]" },
      { title: "Augmentation begins after collection", text: "Sample augmentation has a different starting point: a dataset already exists. Toluna defines HarmonAIze Boost as a post-field tool, while its Personas product generates synthetic respondents. Ask whether your source sample covers the target group and how the provider evaluates the relationships you intend to analyze. More generated rows do not equal more independently recruited people. [4]" },
      { title: "Simulation changes the conditions", text: "Audience simulation explores reactions under specified conditions. The commercial question is whether the modeled population, changed conditions and validation outcomes resemble your own decision. Treat a successful demonstration in one setting as a reason to investigate, not an automatic approval for every setting." },
      { title: "A practical shortlist", text: "Choose the relevant product category, identify the data you can supply, and ask each provider to run the same tightly scoped task. Agree an acceptance criterion before inspecting results. Compare the output, the supporting evidence and the total cost of using it in your workflow. Keep a route back to human research for decisions the model cannot support." },
    ], sources: [
      { title: "Qualtrics: Synthetic Panels", url: "https://www.qualtrics.com/support/survey-platform/distributions-module/synthetic-panels/" },
      { title: "Synthetic Users: Core Concepts", url: "https://docs.syntheticusers.com/guides/core-concepts" },
      { title: "Ipsos: PersonaBot launch", url: "https://www.ipsos.com/en/launch-ipsos-personabot-groundbreaking-ai-powered-solution-enhance-segmentation-research" },
      { title: "Toluna: product definitions", url: "https://tolunacorporate.com/wp-content/uploads/2025/04/Toluna-Group-Terms-of-Business-v2.6_Incl.-HarmonAize_140325_FINAL.pdf" },
    ], related: ["qualtrics-synthetic-panels", "ipsos-personabot", "toluna-boost"] },
  { slug: "synthetic-research-demo-checklist", type: "Buyer guide", title: "The questions to ask before your next synthetic-research demo.", dek: "Take a concrete brief, a test the model has not seen, and a clear definition of a useful answer.", minutes: 4,
    sections: [
      { title: "Bring a real decision", text: "Replace a broad request for accuracy with a bounded task: rank three concepts for a defined audience, explain a measured segment or assess one pricing change. Specify the market, language, input format and outcome. Ask the provider to confirm that the proposed product supports all four." },
      { title: "Ask what the system has seen", text: "Request the origins, age and permitted uses of the grounding data. Establish whether your test answers were ever used to train, tune or select the model. Ask how client data are separated and what happens when the source population changes. ESOMAR's AI buyer questions offer a useful starting framework for this discussion. [1]" },
      { title: "Define what accuracy means", text: "A correlation, a mean error and agreement on the winning concept answer different questions. Request the actual metric, its denominator, the comparison baseline and results for the audience that matters to you. Ask for failures as well as successes. A high overall score can conceal a reversal in a small but commercially important group." },
      { title: "Test the workflow, not just the answer", text: "Ask for an export, the evidence behind one finding and a repeat of the task with a modest wording change. Confirm which controls, question formats and languages are supported. Qualtrics' documented compatibility list illustrates why a product-level check matters even within a familiar research platform. [2]" },
      { title: "Leave with a bounded agreement", text: "Your buying brief should name permitted uses, prohibited uses, refresh frequency, data ownership, deletion terms, support and acceptance tests. Price the whole workflow: setup, data preparation, credits, reviews and any follow-up human research. Keep a written record of the model version and assumptions attached to the test." },
    ], sources: [
      { title: "ESOMAR: 20 questions to help buyers of AI-based services", url: "https://community.esomar.org/uploads/public/library/documents/miscellaneous/20-questions-to-help-buyers-of-ai-based-services.pdf" },
      { title: "Qualtrics: supported survey features", url: "https://www.qualtrics.com/support/survey-platform/distributions-module/synthetic-panels/" },
    ], related: ["electric-twin", "fairgen-twins", "synthetic-users"] },
  { slug: "personas-versus-boosting", type: "Analysis", title: "Personas or sample boosting? The distinction changes your brief.", dek: "Two products can share an AI brand while solving fundamentally different research problems.", minutes: 3,
    sections: [
      { title: "One brand is not one methodology", text: "Toluna's product definitions make a useful distinction. HarmonAIze Boost extends patterns in a collected dataset after fieldwork. Synthetic Personas are generated survey respondents grounded in anonymized first-party panel data. They sit under a related brand, but a buyer should not specify or assess them as the same purchase. [1]" },
      { title: "Match the test to the product", text: "For a boosting brief, examine the starting sample, the target cells, model assumptions and error on withheld observations. For a persona brief, examine the audience grounding, supported stimuli and whether new responses match appropriate human outcomes. Both benefit from external checks, but the checks should reflect what the product is actually doing." },
      { title: "Separate the commercial scope", text: "A quotation should identify the product, the supplied data, the deliverable and the permitted analysis. Specify whether the engagement includes fresh fieldwork, simulated responses, an augmented file or interactive access. Ask for those components to remain distinguishable in the final output. That makes the work easier to buy, interpret and reuse." },
    ], sources: [{ title: "Toluna: terms and product definitions", url: "https://tolunacorporate.com/wp-content/uploads/2025/04/Toluna-Group-Terms-of-Business-v2.6_Incl.-HarmonAize_140325_FINAL.pdf" }], related: ["toluna-personas", "toluna-boost", "fairgen-boost"] },
  { slug: "simile-behavior-and-motivation", type: "Briefing", title: "Simile makes the case for combining behavior with motivation.", dek: "Its What-If Machine essay puts multiple forms of human data at the center of behavioral simulation.", minutes: 2,
    sections: [
      { title: "The company's position", text: "In Building the What-If Machine, Simile's Michael Bernstein describes a model-development approach combining observed actions with surveys, interviews and experiments. The stated ambition is to explore responses to changed conditions, rather than simply extrapolate yesterday's behavior. Simile also describes training confidence models alongside its simulations. These are the company's account of its approach. [1]" },
      { title: "Why it matters to a buyer", text: "SMR's view: the useful procurement question is how a provider connects data types and demonstrates performance on the change you want to test. Ask what has been measured, what has been inferred and how confidence behaves when a new decision falls outside prior examples. A richer input description is a starting point for that conversation, not a substitute for the test." },
    ], sources: [{ title: "Simile: Building the What-If Machine", url: "https://www.simile.com/blog/what-if-machine" }], related: ["simile", "aaru", "electric-twin"] },
];
export function getStory(slug: string) { return stories.find(s => s.slug === slug); }
