export type Story = { slug: string; type: "Buyer guide" | "Analysis" | "Briefing"; title: string; dek: string; minutes: number; sections: { title: string; text: string }[]; sources: { title: string; url: string }[]; related: string[] };
export const stories: Story[] = [
  { slug: "choose-the-right-synthetic-research", type: "Buyer guide", title: "Which synthetic research tool do you need?", dek: "Some tools answer questions. Others work with data you already have. Here's how to choose.", minutes: 3,
    sections: [
      { title: "Start with one question", text: "Say you have three ideas for a new product. You want to know which one is worth testing with customers. That's a useful starting point for a demo. 'Show us your AI' isn't. Write down the question, who the customers are, and what you'll do with the answer." },
      { title: "Want to ask an AI audience questions?", text: "Look at synthetic respondents. These are AI-generated participants that answer surveys or interviews. Qualtrics offers Synthetic Panels inside its survey platform. Synthetic Users lets you describe the audience you want to hear from. Ask the provider to show you how its answers compare with answers from real people like your customers. [1, 2]" },
      { title: "Already know your customer groups?", text: "A digital twin can make that research easier to use. For example, your team could ask questions of a model based on an existing customer group. Ipsos PersonaBot is designed to help teams use their segmentation research this way. Segmentation simply means dividing customers into groups with shared needs or behaviour. [3]" },
      { title: "Need more detail from an existing survey?", text: "Look at sample augmentation, also called boosting. It adds generated responses to a dataset you've already collected. Toluna describes HarmonAIze Boost as a tool used after survey fieldwork. The key question is whether it improves the analysis you need, such as understanding a smaller customer group. Generated responses are not extra people you interviewed. [4]" },
      { title: "Want to explore a change?", text: "Audience simulation tools let you explore questions such as 'What might happen if we change the price?' Give each provider the same example and compare what comes back. Before you buy, agree on what a good result looks like, what data you'll need to supply, and the full cost of running the work." },
    ], sources: [
      { title: "Qualtrics: Synthetic Panels", url: "https://www.qualtrics.com/support/survey-platform/distributions-module/synthetic-panels/" },
      { title: "Synthetic Users: Core Concepts", url: "https://docs.syntheticusers.com/guides/core-concepts" },
      { title: "Ipsos: PersonaBot launch", url: "https://www.ipsos.com/en/launch-ipsos-personabot-groundbreaking-ai-powered-solution-enhance-segmentation-research" },
      { title: "Toluna: product definitions", url: "https://tolunacorporate.com/wp-content/uploads/2025/04/Toluna-Group-Terms-of-Business-v2.6_Incl.-HarmonAize_140325_FINAL.pdf" },
    ], related: ["qualtrics-synthetic-panels", "ipsos-personabot", "toluna-boost"] },
  { slug: "synthetic-research-demo-checklist", type: "Buyer guide", title: "What to ask in a synthetic research demo", dek: "Bring a real question. Ask where the answers come from. Find out what the full job will cost.", minutes: 3,
    sections: [
      { title: "Can we try our own example?", text: "Pick a small job your team actually needs to do. Perhaps you want to compare three messages for first-time buyers. Tell the provider which country and language matter. A demo using your question will tell you more than a polished example chosen by the sales team." },
      { title: "What data is behind this audience?", text: "Ask where the data came from, when it was collected, and which people it covers. Then ask what happens to any customer data you upload. Will it be kept separate? Can you delete it? ESOMAR's questions for buyers of AI services are a useful checklist for this conversation. [1]" },
      { title: "What does your accuracy score mean?", text: "If a provider says a model is '90% accurate', ask: accurate at what? Picking the same winning idea as a human survey is different from predicting how many people will buy. Ask to see results for customers like yours, including examples where the model got the answer wrong." },
      { title: "Can you show us a fair test?", text: "Use a study whose answers were kept out of the model's training and setup. That is often called a holdout test. Ask the provider to make its predictions before you reveal the real results. Then check the parts that matter to your decision, not just one score for the whole study." },
      { title: "What will the complete job cost?", text: "Ask about setup, data preparation, usage limits, exports and support. Check that the tool handles your question types and languages; Qualtrics, for example, documents which survey features its Synthetic Panels support. Leave with a written quote for your actual task and an agreed test of success. [2]" },
    ], sources: [
      { title: "ESOMAR: 20 questions to help buyers of AI-based services", url: "https://community.esomar.org/uploads/public/library/documents/miscellaneous/20-questions-to-help-buyers-of-ai-based-services.pdf" },
      { title: "Qualtrics: supported survey features", url: "https://www.qualtrics.com/support/survey-platform/distributions-module/synthetic-panels/" },
    ], related: ["electric-twin", "fairgen-twins", "synthetic-users"] },
  { slug: "personas-versus-boosting", type: "Analysis", title: "Synthetic personas and sample boosting: what's the difference?", dek: "One creates AI participants. The other builds on a survey you've already run.", minutes: 2,
    sections: [
      { title: "They start in different places", text: "Toluna sells both types of product. Its Synthetic Personas are AI-generated survey respondents based on anonymised data from its own panel. HarmonAIze Boost works with a dataset after the survey has finished. The names sit under the same AI brand, but they describe different jobs. [1]" },
      { title: "Here's a simple example", text: "Imagine you've surveyed customers but have few answers from a group you care about. A boosting tool may be worth testing for that analysis. Now imagine you're exploring a new product idea and want an AI audience to answer questions about it. That's closer to a persona brief. These are examples of how to frame a task, not two names for the same service." },
      { title: "Ask for the right test and quote", text: "For boosting, ask how much real survey data the tool needs and test it against answers you kept aside. For personas, ask what the audience is based on and compare its answers with a relevant human study. The quote should say exactly what you'll receive: new human interviews, AI responses, an expanded dataset, or access to a tool." },
    ], sources: [{ title: "Toluna: terms and product definitions", url: "https://tolunacorporate.com/wp-content/uploads/2025/04/Toluna-Group-Terms-of-Business-v2.6_Incl.-HarmonAize_140325_FINAL.pdf" }], related: ["toluna-personas", "toluna-boost", "fairgen-boost"] },
  { slug: "simile-behavior-and-motivation", type: "Briefing", title: "Why Simile combines what people do with what they say", dek: "Purchase records show a choice. Interviews can help explain it. Simile wants to bring those views together.", minutes: 2,
    sections: [
      { title: "Two parts of the same story", text: "Imagine a customer stops buying a product. Their purchase history shows the change, but it doesn't tell you why. Was it the price, the product, or something else? In Building the What-If Machine, Simile describes combining people's actions with surveys, interviews and experiments to model how they might respond to change. [1]" },
      { title: "What to ask in a demo", text: "For a buyer, the useful question is simple: can this approach help with the change you're considering? Bring an example, such as a new price or product. Ask which data the model uses and how the provider checked its predictions against real outcomes. You want to see how the different inputs help answer your question, not just a list of the data available." },
    ], sources: [{ title: "Simile: Building the What-If Machine", url: "https://www.simile.com/blog/what-if-machine" }], related: ["simile", "aaru", "electric-twin"] },
];
export function getStory(slug: string) { return stories.find(s => s.slug === slug); }
