import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, GitCompareArrows } from "lucide-react";
import { products, getProduct } from "@/lib/directory";
import { PublicationFrame, ProductMark, RelatedProducts, ProductVisual } from "@/components/PublicationUI";
export function generateStaticParams() { return products.map(p => ({ slug: p.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const p = getProduct(slug); return p ? { title: `${p.company} ${p.name} | SMR Product Profile`, description: p.summary, alternates: { canonical: `/directory/${slug}` } } : { title: "Product not found | SMR" }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const p = getProduct(slug); if (!p) notFound();
  const related = products.filter(other => other.category === p.category && other.slug !== p.slug).slice(0, 3).map(p => p.slug);
  return <PublicationFrame><div className="pub-wrap pub-profile"><Link className="pub-text-link" href="/directory"><ArrowLeft size={16} /> Product directory</Link><header className="pub-profile-heading"><ProductMark product={p} /><div><p className="pub-eyebrow">{p.category}</p><h1>{p.company}</h1><p className="pub-profile-product">{p.name}</p></div></header><div className="pub-profile-layout"><article><p className="pub-profile-summary">{p.summary}</p><div className="pub-profile-facts"><div><h2>Product category</h2><p>{p.category}</p></div><div><h2>Use cases</h2><p>{p.uses.join(" / ")}</p></div><div><h2>Data grounding</h2><p>{p.data}</p></div><div><h2>Access & pricing</h2><p>{p.access}. {p.pricing}.</p></div></div><section className="pub-demo-question"><p className="pub-eyebrow">TAKE THIS TO YOUR DEMO / SMR PERSPECTIVE</p><h2>{p.question}</h2><Link href="/insights/synthetic-research-demo-checklist" className="pub-text-link">The full demo checklist <ArrowUpRight size={16} /></Link></section>{p.slug === "fairgen-twins" && <ProductVisual />}</article><aside className="pub-profile-sidebar"><h2>Explore {p.company}</h2><a className="pub-button" href={p.source} target="_blank" rel="noopener noreferrer">Visit provider <ArrowUpRight size={17} /></a><Link className="pub-button pub-button-outline" href={`/compare?products=${p.slug}`}><GitCompareArrows size={17} /> Add to comparison</Link><hr /><p className="pub-eyebrow">PROFILE SOURCES</p><a className="pub-source-link" href={p.source} target="_blank" rel="noopener noreferrer">{p.sourceTitle} <ArrowUpRight size={14} /></a><p className="pub-caption">Checked 6 September 2026. Product scope is drawn from provider documentation, not an SMR performance test.</p><Link href={`/contact?interest=${encodeURIComponent(`Correction: ${p.company} ${p.name}`)}`} className="pub-text-link">Suggest a correction <ArrowUpRight size={14} /></Link><Link href="/methodology" className="pub-text-link">Our editorial standards <ArrowUpRight size={14} /></Link></aside></div><RelatedProducts ids={related} /></div></PublicationFrame>;
}
