import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Search } from "lucide-react";
import { PublicationFrame, StoryCard, BriefingBand, ProductLink, ProductVisual } from "@/components/PublicationUI";
import { categories, categoryDescriptions, products, providerCount } from "@/lib/directory";
import { stories } from "@/lib/publication";
export const metadata: Metadata = { title: "Synthetic Market Research | The Industry, Explained", description: "Find and compare synthetic research products. Explore providers, buyer guides and developments in synthetic audiences, digital twins and sample augmentation.", alternates: { canonical: "/" } };
export default function Home() {
  return <PublicationFrame><section className="pub-home-masthead pub-wrap"><div className="pub-edition"><span>THE SYNTHETIC RESEARCH INDUSTRY</span><span>DIRECTORY / INSIGHT / PERSPECTIVE</span></div><h1>Synthetic market research.</h1><div className="pub-home-intro"><p>The companies. The products. The questions that matter.</p><Link href="/directory" className="pub-search-link"><Search size={18} /> Find your next research tool <ArrowRight size={18} /></Link></div></section>
    <section className="pub-wrap pub-front-grid"><article className="pub-lead-story"><p className="pub-eyebrow">THE BUYER&apos;S GUIDE <span>/ SEPTEMBER 2026</span></p><h2><Link href={`/insights/${stories[0].slug}`}>One industry.<br /><em>Very different tools.</em></Link></h2><p>{stories[0].dek}</p><Link href={`/insights/${stories[0].slug}`} className="pub-text-link">Understand the landscape <ArrowRight size={17} /></Link><div className="pub-lead-rule"><span>{products.length} product profiles</span><span>{providerCount} providers</span><span>4 product categories</span></div></article><aside className="pub-front-side"><ProductVisual /><div className="pub-inside-product"><p className="pub-eyebrow">INSIDE THE PRODUCT</p><Link href="/directory/fairgen-twins">Fairgen Twins: from research data to reusable audiences <ArrowUpRight size={19} /></Link></div></aside></section>
    <section className="pub-wrap pub-section"><div className="pub-section-title"><h2>Find the right kind of research.</h2><Link href="/directory" className="pub-text-link">All products <ArrowRight size={17} /></Link></div><div className="pub-category-grid">{categories.map((c, i) => <Link href={`/directory?category=${encodeURIComponent(c)}`} key={c}><span className="pub-category-number">0{i + 1}</span><h3>{c} <ArrowUpRight size={18} /></h3><p>{categoryDescriptions[c]}</p><small>{products.filter(p => p.category === c).length} products</small></Link>)}</div></section>
    <section className="pub-provider-band"><div className="pub-wrap"><div className="pub-section-title"><h2>Meet the providers.</h2><Link href="/directory" className="pub-text-link">Explore the directory <ArrowRight size={17} /></Link></div><div className="pub-related-grid">{["qualtrics-synthetic-panels", "toluna-personas", "ipsos-personabot", "aaru", "electric-twin", "simile"].map(id => <ProductLink key={id} product={products.find(p => p.slug === id)!} />)}</div></div></section>
    <section className="pub-wrap pub-section"><div className="pub-section-title"><h2>The reading list.</h2><Link href="/insights" className="pub-text-link">All insights <ArrowRight size={17} /></Link></div><div className="pub-story-grid">{stories.slice(1).map((s, i) => <StoryCard key={s.slug} story={s} number={i + 1} />)}</div></section><BriefingBand />
    <section className="pub-wrap pub-commercial-band"><div><p className="pub-eyebrow">FOR PROVIDERS</p><h2>Be part of the conversation.</h2><p>Introduce your product to researchers evaluating the next generation of insights tools.</p></div><div><Link href="/submit" className="pub-text-link">Submit a free listing <ArrowUpRight size={17} /></Link><Link href="/advertise" className="pub-text-link">Explore sponsorship <ArrowUpRight size={17} /></Link></div></section>
  </PublicationFrame>;
}
