"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, Download, Link2, Check } from "lucide-react";
import { products, getProduct, checked } from "@/lib/directory";
export default function ProductCompare({ initial }: { initial: string[] }) {
  const [ids, setIds] = useState<string[]>([...initial, "", "", ""].slice(0, 3));
  const [copied, setCopied] = useState(false);
  const [message, setMessage] = useState("");
  const chosen = ids.map(getProduct).filter(p => !!p);
  const rows = [["Product category", "category"], ["Product", "name"], ["Overview", "summary"], ["Data grounding / provider account", "data"], ["Access", "access"], ["Pricing / check inclusions", "pricing"], ["Question for your demo / SMR", "question"]] as const;
  return <section className="pub-wrap pub-compare"><div className="pub-compare-selectors">{ids.map((id, index) => <label key={index}>Product {index + 1}<select value={id} onChange={e => { const next = [...ids]; next[index] = e.target.value; setIds(next); setCopied(false); const param = next.filter(Boolean).join(","); history.replaceState(null, "", `/compare${param ? `?products=${param}` : ""}`); }}><option value="">Choose a product</option>{products.map(p => <option key={p.slug} value={p.slug} disabled={ids.includes(p.slug) && p.slug !== id}>{p.company} / {p.name}</option>)}</select></label>)}</div>
    {chosen.length < 2 ? <div className="pub-empty"><h2>Build a useful comparison.</h2><p>Select two or three products above, or add them from the directory.</p><Link href="/directory" className="pub-text-link">Browse products <ArrowUpRight size={16} /></Link></div> : <><div className="pub-compare-tools"><p>Provider documentation checked 6 September 2026</p><button title="Copy comparison link" onClick={async () => { try { await navigator.clipboard.writeText(`${location.origin}/compare?products=${ids.filter(Boolean).join(",")}`); setCopied(true); setMessage("Link copied."); } catch { setMessage("Copy the comparison URL from your address bar."); } }}>{copied ? <Check size={17} /> : <Link2 size={17} />} Copy link</button><button onClick={() => { const csv = [["SMR product comparison", ...chosen.map(p => p.company)], ...rows.map(([label, key]) => [label, ...chosen.map(p => p[key])]), ["Source", ...chosen.map(p => p.source)], ["Checked", ...chosen.map(() => checked)], ["Scope", ...chosen.map(() => "Provider documentation; not independent performance testing")]].map(row => row.map(cell => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "SMR-product-comparison.csv"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}><Download size={17} /> Export CSV</button></div><p className="pub-sr" role="status">{message}</p><div className="pub-table-scroll" tabIndex={0} role="region" aria-label="Product comparison table"><table className="pub-compare-table"><caption className="pub-sr">Comparison of {chosen.map(p => p.company + " " + p.name).join(", ")}</caption><thead><tr><th scope="col">Compare products</th>{chosen.map(p => <th scope="col" key={p.slug}><Link href={`/directory/${p.slug}`}>{p.company}<small>{p.name}</small></Link></th>)}</tr></thead><tbody>{rows.map(([label, key]) => <tr key={key}><th scope="row">{label}</th>{chosen.map(p => <td key={p.slug}>{p[key]}</td>)}</tr>)}<tr><th scope="row">Primary source</th>{chosen.map(p => <td key={p.slug}><a href={p.source} target="_blank" rel="noopener noreferrer">Provider documentation <ArrowUpRight size={14} /></a></td>)}</tr></tbody></table></div><p className="pub-directory-note">SMR compares documented product scope, not performance scores. Confirm availability and commercial terms directly with the provider.</p></>}
  </section>;
}
